version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: myappuser
      POSTGRES_PASSWORD: myapppassword
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init-db:/docker-entrypoint-initdb.d
    networks:
      - webnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  web:
    build: ./web
    depends_on:
      - db
    environment:
      DATABASE_NAME: myappdb
      DATABASE_USER: myappuser
      DATABASE_PASSWORD: myapppassword
      DATABASE_HOST: db
    ports:
      - "8000:8000"
    networks:
      - webnet
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

volumes:
  db_data:

networks:
  webnet:
    driver: overlay
