---
- name: Initialize Docker Swarm on Manager
  hosts: manager
  become: yes
  tasks:
    - name: Initialize Swarm
      shell: docker swarm init --advertise-addr {{ ansible_host }}
      register: swarm_init
      ignore_errors: yes

    - name: Get join token for workers
      shell: docker swarm join-token worker -q
      register: worker_token
      when: swarm_init.rc == 0

    - name: Set fact for worker token
      set_fact:
        swarm_worker_token: "{{ worker_token.stdout }}"

- name: Join Workers to Swarm
  hosts: worker_a,worker_b
  become: yes
  tasks:
    - name: Join swarm
      shell: docker swarm join --token {{ hostvars['manager']['swarm_worker_token'] }} {{ hostvars['manager']['ansible_host'] }}:2377
      ignore_errors: yes
